#!/bin/sh
set -e

# Load secrets generated by the setup service before the main process starts.
if [ -f "/app/secrets/runtime.env" ]; then
  set -a
  . /app/secrets/runtime.env
  set +a
fi

exec "$@"
