#!/usr/bin/env bash
# WhatsUpShop — Production migration runner.
# Runs as the migrate one-shot service in docker-compose.yml.
# Exits 0 on success; non-zero on any failure (blocks backend startup).
set -euo pipefail

SECRETS_DIR="/app/secrets"
RUNTIME_ENV="${SECRETS_DIR}/runtime.env"

# ── Load secrets generated by the setup service ───────────────────────────────
if [[ ! -f "${RUNTIME_ENV}" ]]; then
  echo "[migrate][ERROR] ${RUNTIME_ENV} not found." >&2
  echo "[migrate][ERROR] The preflight service should have caught this. Check setup logs." >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "${RUNTIME_ENV}"
set +a

# ── Colour helpers ────────────────────────────────────────────────────────────
log()  { echo "[migrate] $*"; }
err()  { echo "[migrate][ERROR] $*" >&2; }

# ── 1. Validate required environment variables ────────────────────────────────
REQUIRED_VARS=(DB_HOST DB_PORT DB_USER DB_PASSWORD DB_NAME)
missing=()
for var in "${REQUIRED_VARS[@]}"; do
  [[ -z "${!var:-}" ]] && missing+=("$var")
done

if [[ ${#missing[@]} -gt 0 ]]; then
  err "Missing required environment variables: ${missing[*]}"
  exit 1
fi

# ── 2. Wait for MySQL to be ready using DB_USER/DB_PASSWORD ───────────────────
log "Waiting for database at ${DB_HOST}:${DB_PORT} (user: ${DB_USER})..."

MAX_ATTEMPTS=60
attempt=0
until mysqladmin ping \
  --host="${DB_HOST}" \
  --port="${DB_PORT}" \
  --user="${DB_USER}" \
  --password="${DB_PASSWORD}" \
  --silent 2>/dev/null; do
  attempt=$((attempt + 1))
  if [[ $attempt -ge $MAX_ATTEMPTS ]]; then
    err "Could not connect to MySQL using DB_USER/DB_PASSWORD after ${MAX_ATTEMPTS} attempts."
    err ""
    err "Real MySQL error:"
    # Run once without stderr suppression to expose the actual MySQL error.
    mysqladmin ping \
      --host="${DB_HOST}" \
      --port="${DB_PORT}" \
      --user="${DB_USER}" \
      --password="${DB_PASSWORD}" \
      --silent 2>&1 || true
    err ""
    err "Possible causes:"
    err "  1. mysql_data was created with different secrets (volume desync)."
    err "     app_secrets was deleted or regenerated after the DB was initialized."
    err "  2. DB_USER or DB_NAME changed after first install."
    err "  3. The database container is unhealthy or still starting."
    err ""
    err "Recovery:"
    err "  - PRODUCTION: Restore app_secrets/runtime.env from runtime.env.backup"
    err "    or external backup. Do NOT delete mysql_data."
    err "  - TEST INSTALL (no real data): Delete BOTH mysql_data AND app_secrets"
    err "    volumes and redeploy from scratch."
    err ""
    err "Check setup logs:        docker compose logs setup"
    err "Check DB logs:           docker compose logs db"
    err "Check db-user-init logs: docker compose logs db-user-init"
    exit 1
  fi
  log "  attempt ${attempt}/${MAX_ATTEMPTS} — retrying in 2s..."
  sleep 2
done

log "Database ready."

# ── 3. Backup ─────────────────────────────────────────────────────────────────
AUTO_BACKUP="${AUTO_BACKUP_BEFORE_MIGRATE:-true}"
BACKUP_DIR="/app/backups"
mkdir -p "${BACKUP_DIR}"

if [[ "${AUTO_BACKUP}" != "false" ]]; then
  TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
  BACKUP_FILE="${BACKUP_DIR}/${DB_NAME}_pre_migrate_${TIMESTAMP}.sql.gz"

  log "Creating backup → ${BACKUP_FILE}"

  mysqldump \
    --host="${DB_HOST}" \
    --port="${DB_PORT}" \
    --user="${DB_USER}" \
    --password="${DB_PASSWORD}" \
    --single-transaction \
    --routines \
    --triggers \
    "${DB_NAME}" | gzip > "${BACKUP_FILE}"

  log "Backup created: $(du -sh "${BACKUP_FILE}" | cut -f1)"

  # ── Retention: delete backups older than BACKUP_RETENTION_DAYS ──────────────
  RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
  if [[ "${RETENTION_DAYS}" =~ ^[0-9]+$ ]] && [[ "${RETENTION_DAYS}" -gt 0 ]]; then
    deleted=$(find "${BACKUP_DIR}" \
      -maxdepth 1 \
      -name "${DB_NAME}_pre_migrate_*.sql.gz" \
      -mtime +"${RETENTION_DAYS}" \
      -print \
      -delete | wc -l | tr -d ' ')
    [[ "${deleted}" -gt 0 ]] && log "Purged ${deleted} backup(s) older than ${RETENTION_DAYS} days."
  fi
else
  log "AUTO_BACKUP_BEFORE_MIGRATE=false — skipping backup."
fi

# ── 4. Run Drizzle migrations ─────────────────────────────────────────────────
log "Running Drizzle migrations..."

bun run db:migrate

log "Migrations completed successfully."
