#!/usr/bin/env bash
# WhatsUpShop — Production migration runner.
# Runs as the migrate one-shot service in docker-compose.yml.
# Exits 0 on success; non-zero on any failure (blocks backend startup).
set -euo pipefail

SECRETS_DIR="/app/secrets"
RUNTIME_ENV="${SECRETS_DIR}/runtime.env"

# ── Load secrets generated by the setup service ───────────────────────────────
if [[ ! -f "${RUNTIME_ENV}" ]]; then
  echo "[migrate][ERROR] ${RUNTIME_ENV} not found." >&2
  echo "[migrate][ERROR] The preflight service should have caught this. Check setup logs." >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "${RUNTIME_ENV}"
set +a

# ── Helpers ───────────────────────────────────────────────────────────────────
log()  { echo "[migrate] $*"; }
err()  { echo "[migrate][ERROR] $*" >&2; }

# ── 1. Validate required environment variables ────────────────────────────────
REQUIRED_VARS=(DB_HOST DB_PORT DB_USER DB_PASSWORD DB_NAME)
missing=()
for var in "${REQUIRED_VARS[@]}"; do
  [[ -z "${!var:-}" ]] && missing+=("$var")
done

if [[ ${#missing[@]} -gt 0 ]]; then
  err "Missing required environment variables: ${missing[*]}"
  exit 1
fi

# ── 2. Wait for MySQL — real SQL connection test ──────────────────────────────
log "Waiting for SQL connection at ${DB_HOST}:${DB_PORT} (user: ${DB_USER}, db: ${DB_NAME})..."

MAX_ATTEMPTS=60
attempt=0
until MYSQL_PWD="${DB_PASSWORD}" mysql \
  --protocol=TCP \
  --host="${DB_HOST}" \
  --port="${DB_PORT}" \
  --user="${DB_USER}" \
  --database="${DB_NAME}" \
  --execute="SELECT 1;" \
  > /dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [[ $attempt -ge $MAX_ATTEMPTS ]]; then
    err "Could not run SELECT 1 using DB_USER/DB_PASSWORD on DB_NAME after ${MAX_ATTEMPTS} attempts."
    err ""
    err "Real MySQL error:"
    MYSQL_PWD="${DB_PASSWORD}" mysql \
      --protocol=TCP \
      --host="${DB_HOST}" \
      --port="${DB_PORT}" \
      --user="${DB_USER}" \
      --database="${DB_NAME}" \
      --execute="SELECT 1;" 2>&1 || true
    err ""
    err "Possible causes:"
    err "  1. DB_USER does not have permissions on DB_NAME."
    err "  2. DB_NAME does not exist."
    err "  3. DB_PASSWORD does not match the MySQL user."
    err "  4. MySQL client cannot authenticate (plugin mismatch)."
    err "  5. mysql_data and app_secrets are out of sync."
    err ""
    err "Recovery:"
    err "  - PRODUCTION: Restore app_secrets/runtime.env from runtime.env.backup"
    err "    or external backup. Do NOT delete mysql_data."
    err "  - TEST INSTALL (no real data): Delete BOTH mysql_data AND app_secrets"
    err "    volumes and redeploy from scratch."
    err ""
    err "Check setup logs:        docker compose logs setup"
    err "Check DB logs:           docker compose logs db"
    err "Check db-user-init logs: docker compose logs db-user-init"
    exit 1
  fi
  log "  attempt ${attempt}/${MAX_ATTEMPTS} — retrying in 2s..."
  sleep 2
done

log "Database SQL connection ready."

# ── 3. Backup ─────────────────────────────────────────────────────────────────
AUTO_BACKUP="${AUTO_BACKUP_BEFORE_MIGRATE:-true}"
BACKUP_DIR="/app/backups"
mkdir -p "${BACKUP_DIR}"

if [[ "${AUTO_BACKUP}" != "false" ]]; then
  TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
  BACKUP_FILE="${BACKUP_DIR}/${DB_NAME}_pre_migrate_${TIMESTAMP}.sql.gz"

  log "Creating backup → ${BACKUP_FILE}"

  if ! MYSQL_PWD="${DB_PASSWORD}" mysqldump \
    --protocol=TCP \
    --host="${DB_HOST}" \
    --port="${DB_PORT}" \
    --user="${DB_USER}" \
    --no-tablespaces \
    --single-transaction \
    --routines \
    --triggers \
    "${DB_NAME}" | gzip > "${BACKUP_FILE}"; then
    err "Backup failed. Aborting migrations."
    rm -f "${BACKUP_FILE}"
    exit 1
  fi

  log "Backup created: $(du -sh "${BACKUP_FILE}" | cut -f1)"

  # ── Retention: delete backups older than BACKUP_RETENTION_DAYS ──────────────
  RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-7}"
  if [[ "${RETENTION_DAYS}" =~ ^[0-9]+$ ]] && [[ "${RETENTION_DAYS}" -gt 0 ]]; then
    deleted=$(find "${BACKUP_DIR}" \
      -maxdepth 1 \
      -name "${DB_NAME}_pre_migrate_*.sql.gz" \
      -mtime +"${RETENTION_DAYS}" \
      -print \
      -delete | wc -l | tr -d ' ')
    [[ "${deleted}" -gt 0 ]] && log "Purged ${deleted} backup(s) older than ${RETENTION_DAYS} days."
  fi
else
  log "AUTO_BACKUP_BEFORE_MIGRATE=false — skipping backup."
fi

# ── 4. Run Drizzle migrations ─────────────────────────────────────────────────
log "Running Drizzle migrations..."

if ! bunx drizzle-kit migrate --config=drizzle.config.ts; then
  err "Drizzle migration failed."
  exit 1
fi

log "Migrations completed successfully."
